### ISSUE TITLE
microstutters with http status installed

### ISSUE THREAD

**Issue by ragesaq** [opl-/beatsaber-http-status#25] opened 2019-08-27 00:03 UTC
I've used http status for a long time but since the most recent camelia 3pack release of beat saber I've gotten microstutters about every 90 seconds on every map. Removing http status plugin only resolved this issue 100%.
I've talked to several other people who use it and had this issue they confirmed removing http status plugin resolved the issue.

**Comment by opl-** [comment] 2019-08-27 15:21
Duplicate of #3. I'm aware of the issue but haven't been able to reproduce it myself, so I can't really fix it. That being said, over the months I've received a few reports of this happening and so I'll keep it in mind. Maybe I'll think of some solution.

**Closed by opl-** 2019-08-27 15:21 UTC
